<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Place;

/**
 * @var array<array<Place>> $columns
 */

?>

<div class="row">
    <h5 class="col list_label text-center">
        <?= I18N::translate('Place list') ?>
            </h5>
</div>
<div class="row">
    <?php foreach ($columns as $column) : ?>
        <ul class="col wt-page-options-value me-1 list-unstyled">
            <?php foreach ($column as $place) : ?>
                <li><?= $place->fullName(true) ?></li>
            <?php endforeach ?>
        </ul>
    <?php endforeach ?>
</div>
